# Generated by Django 5.2.3 on 2025-06-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discrebtion',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
