# Generated by Django 5.2.3 on 2025-06-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_discrebtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='discrebtion',
            new_name='description',
        ),
    ]
